version: '2.3'
services:
  kibana:
    container_name: kibana
    build: ./kibana
    image: cisien/kibana
    ports:
      - "5601:5601"
    restart: always
    depends_on:
      - "elasticsearch"
  elasticsearch:
    container_name: elasticsearch
    build: ./elasticsearch
    image: cisien/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic-data:c:\data
    restart: always
    mem_limit: 3684354560

volumes:
  elastic-data:
    
networks:
  default:
    external:
      name: nat