version: '2.3'
services:
  kibana:
    build: ./kibana
    image: cisien/kibana
    ports:
      - "5601:5601"
    restart: always
    depends_on:
      - "elasticsearch"
  elasticsearch:
    build: ./elasticsearch
    image: cisien/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es:c:/data
    restart: always
    mem_limit: 2684354560

volumes:
  es:

networks:
  default:
    external:
      name: nat